language: python
python:
    - "3.5"
install:
    - sudo apt-get install libtag1-dev
    - pip install -r requirements.txt
    - pip install coveralls
    - pip install nose
script:
    nosetests --with-coverage --cover-erase --cover-package=rfat.py
after_success:
    coveralls

